#server.port=8084
#spring.data.mongodb.database=pizzadelivery
#spring.data.mongodb.uri=mongodb://localhost:27017/pizzadelivery
#server.error.include-message=always

server:
  port: 8084

spring:
  data:
    mongodb:
      url: mongodb://localhost:27017/pizzadelivery
    application:
      name: pizza-order

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_SERVER_IP:localhost}:8761/eureka
    fetchRegistry: true
    registerWithEureka: true
  cloud:
    compatibility-verifier:
      enabled: false

