#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://localhost:3306/pizzadeliverysys/registeruser?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=krishna@1232
#spring.jpa.show-sql=true
#server.port=8099
#driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect

server:
    port: 8099

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/pizzadeliverysys/registeruser?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
        username: root
        password: krishna@1232
        driver-class-name: com.mysql.cj.jdbc.Driver

    cloud:
        compatibility-verifier:
            enabled: false

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL57Dialect

        application:
            name: user

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
        fetchRegistry: true
        registerWithEureka: true
    instance:
        prefer-ip-address: true
